name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Setup environment variables
        run: |
          touch .env
          echo AUTH_ORIGIN=${{ secrets.AUTH_ORIGIN }} >> .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          cp ecosystem.config.cjs .output/
          cp .env .output/

      - name: rsync .env and config
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./.output/*
          remote_path: /var/www/ai-assistant/
          remote_host: 34.243.12.73
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Deploy application with PM2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Start the SSH agent
          eval $(ssh-agent -s)
          # Add the SSH key stored in SSH_PRIVATE_KEY secret to the agent
          ssh-add <(echo "$SSH_PRIVATE_KEY")
          # Disable SSH host key checking for the current command
          SSH_CMD="ssh -o StrictHostKeyChecking=no"

          $SSH_CMD ubuntu@34.243.12.73 'bash -s' < env $(cat .env | grep -v \"#\" | xargs) pm2 start ecosystem.config.cjs
