name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Setup environment variables
        run: |
          touch .env
          echo AUTH_ORIGIN=${{ secrets.AUTH_ORIGIN }} >> .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env

      - name: Custom rsync deployments
        run: |
          rsync -avzr --delete ./.output/server/ ubuntu@34.243.12.73:/var/www/ai-assistant/
          rsync -avzr --delete ecosystem.config.cjs ubuntu@34.243.12.73:/var/www/ai-assistant/
          rsync -avzr --delete .env ubuntu@34.243.12.73:/var/www/ai-assistant/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install PM2
        run: bun install --global pm2
      - name: Deploy
        run: env $(cat .env | grep -v \"#\" | xargs) pm2 start ecosystem.config.cjs
