name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Setup environment variables
        run: |
          touch .env
          echo AUTH_ORIGIN=${{ secrets.AUTH_ORIGIN }} >> .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --include=.output --include=.env --include ecosystem.config.cjs
          path: ./*
          remote_path: /var/www/ai-assistant/
          remote_host: 34.243.12.73
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Install PM2
        run: bun install --global pm2
      - name: Deploy
        run: env $(cat .env | grep -v \"#\" | xargs) pm2 start ecosystem.config.cjs
